/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamingRouteImport } from './routes/streaming'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as HorairesRouteImport } from './routes/horaires'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertesRouteImport } from './routes/alertes'
import { Route as ActusRouteImport } from './routes/actus'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SportsSportRouteImport } from './routes/sports.$sport'

const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const HorairesRoute = HorairesRouteImport.update({
  id: '/horaires',
  path: '/horaires',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertesRoute = AlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const ActusRoute = ActusRouteImport.update({
  id: '/actus',
  path: '/actus',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSportRoute = SportsSportRouteImport.update({
  id: '/$sport',
  path: '/$sport',
  getParentRoute: () => SportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actus': typeof ActusRoute
  '/alertes': typeof AlertesRoute
  '/auth': typeof AuthRoute
  '/horaires': typeof HorairesRoute
  '/scores': typeof ScoresRoute
  '/sports': typeof SportsRouteWithChildren
  '/streaming': typeof StreamingRoute
  '/sports/$sport': typeof SportsSportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actus': typeof ActusRoute
  '/alertes': typeof AlertesRoute
  '/auth': typeof AuthRoute
  '/horaires': typeof HorairesRoute
  '/scores': typeof ScoresRoute
  '/sports': typeof SportsRouteWithChildren
  '/streaming': typeof StreamingRoute
  '/sports/$sport': typeof SportsSportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actus': typeof ActusRoute
  '/alertes': typeof AlertesRoute
  '/auth': typeof AuthRoute
  '/horaires': typeof HorairesRoute
  '/scores': typeof ScoresRoute
  '/sports': typeof SportsRouteWithChildren
  '/streaming': typeof StreamingRoute
  '/sports/$sport': typeof SportsSportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/actus'
    | '/alertes'
    | '/auth'
    | '/horaires'
    | '/scores'
    | '/sports'
    | '/streaming'
    | '/sports/$sport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/actus'
    | '/alertes'
    | '/auth'
    | '/horaires'
    | '/scores'
    | '/sports'
    | '/streaming'
    | '/sports/$sport'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/actus'
    | '/alertes'
    | '/auth'
    | '/horaires'
    | '/scores'
    | '/sports'
    | '/streaming'
    | '/sports/$sport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActusRoute: typeof ActusRoute
  AlertesRoute: typeof AlertesRoute
  AuthRoute: typeof AuthRoute
  HorairesRoute: typeof HorairesRoute
  ScoresRoute: typeof ScoresRoute
  SportsRoute: typeof SportsRouteWithChildren
  StreamingRoute: typeof StreamingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horaires': {
      id: '/horaires'
      path: '/horaires'
      fullPath: '/horaires'
      preLoaderRoute: typeof HorairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertes': {
      id: '/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actus': {
      id: '/actus'
      path: '/actus'
      fullPath: '/actus'
      preLoaderRoute: typeof ActusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/$sport': {
      id: '/sports/$sport'
      path: '/$sport'
      fullPath: '/sports/$sport'
      preLoaderRoute: typeof SportsSportRouteImport
      parentRoute: typeof SportsRoute
    }
  }
}

interface SportsRouteChildren {
  SportsSportRoute: typeof SportsSportRoute
}

const SportsRouteChildren: SportsRouteChildren = {
  SportsSportRoute: SportsSportRoute,
}

const SportsRouteWithChildren =
  SportsRoute._addFileChildren(SportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActusRoute: ActusRoute,
  AlertesRoute: AlertesRoute,
  AuthRoute: AuthRoute,
  HorairesRoute: HorairesRoute,
  ScoresRoute: ScoresRoute,
  SportsRoute: SportsRouteWithChildren,
  StreamingRoute: StreamingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
